#! /bin/sh

port=$2
origin=$4
name=$6
username=$8
keyfile=${10}


# Stop HTTP servers

# N. Virginia
ssh '-i' $keyfile $username@ec2-52-0-73-113.compute-1.amazonaws.com 'cd ~; /usr/bin/python ./stopserver.py ' $username $port & > /dev/null


# Ireland
ssh '-i' $keyfile $username@ec2-52-16-219-28.eu-west-1.compute.amazonaws.com 'cd ~; /usr/bin/python ./stopserver.py ' $username $port & > /dev/null


# Oregon
ssh '-i' $keyfile $username@ec2-52-11-8-29.us-west-2.compute.amazonaws.com 'cd ~; /usr/bin/python ./stopserver.py ' $username $port & > /dev/null


# N. California
ssh '-i' $keyfile $username@ec2-52-8-12-101.us-west-1.compute.amazonaws.com 'cd ~; /usr/bin/python ./stopserver.py ' $username $port & > /dev/null


# Frankfurt
ssh '-i' $keyfile $username@ec2-52-28-48-84.eu-central-1.compute.amazonaws.com 'cd ~; /usr/bin/python ./stopserver.py ' $username $port & > /dev/null


# Tokyo
ssh '-i' $keyfile $username@ec2-52-68-12-77.ap-northeast-1.compute.amazonaws.com 'cd ~; /usr/bin/python ./stopserver.py ' $username $port & > /dev/null


# Singapore
ssh '-i' $keyfile $username@ec2-52-74-143-5.ap-southeast-1.compute.amazonaws.com 'cd ~; /usr/bin/python ./stopserver.py ' $username $port & > /dev/null


# Sydney
ssh '-i' $keyfile $username@ec2-52-64-63-125.ap-southeast-2.compute.amazonaws.com 'cd ~; /usr/bin/python ./stopserver.py ' $username $port & > /dev/null


# Sao Paulo
ssh '-i' $keyfile $username@ec2-54-94-214-108.sa-east-1.compute.amazonaws.com 'cd ~; /usr/bin/python ./stopserver.py ' $username $port & > /dev/null


# Stop DNS server
ssh '-i' $keyfile $username@cs5700cdnproject.ccs.neu.edu 'cd ~; /usr/bin/python ./stopserver.py ' $username $port & > /dev/null


